version: '3.9'

networks:
  default:
    external: true
    name: ${NETWORK_NAME}

services:
  testing_nginx:
    container_name: "testing.${ENVIRONMENT}.nginx"
    image: nginx:latest
    restart: always
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - testing_php
    networks:
      default:
        aliases:
          - "testing.${ENVIRONMENT}.nginx"

  testing_php:
    container_name: "testing.${ENVIRONMENT}.php-fpm"
    build:
      context: docker/php
      args:
        - USER_ID
        - GROUP_ID
    volumes:
      - ./app:/var/www/testing
      - ./docker/php/entrypoint.sh:/entrypoint.sh
    depends_on:
      - testing_mysql
    networks:
      default:
        aliases:
          - "testing.${ENVIRONMENT}.php-fpm"

  testing_mysql:
    container_name: "testing.${ENVIRONMENT}.mysql"
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER_NAME}"
      MYSQL_PASSWORD: "${MYSQL_USER_PASSWORD}"
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      default:
        aliases:
          - "testing.${ENVIRONMENT}.mysql"
